### ISSUE TITLE
Pipeline error at step 4B

### ISSUE THREAD

**Issue by XuelinWangTvT** [SAND-Lab/AnalysisPipeline#20]
<img width="1437" alt="Screenshot 2022-08-18 at 12 43 54" src="https://user-images.githubusercontent.com/108819659/185449942-95ee75ba-6abf-4364-badf-83beca9538b0.png">

Hello, I encountered another error when running the pipeline around step 4B. Could you please help me to take a look at it? Thank you so much! Also, David says he sometimes encounter this issue as well.

**Comment by Timothysit** [comment]
Hi Xue Lin, can you let me know which lags are you running the with? It may be because currently `TrialLandscapeDensity` assumes a lag of 15 ms

**Comment by XuelinWangTvT** [comment]
Hello Tim, I'm using a lag of 15ms

**Comment by Timothysit** [comment]
Okay, the next thing to check is whether you are running step 4B from previously analyzed data, or did you run through all the steps? I wonder whether it is because in the prior analysis the participation coefficient (PC) (or 15 ms lag) were not calculated

**Comment by XuelinWangTvT** [comment]
I started running pipeline from step 3 today, so running from previously analyzed data.

**Comment by Timothysit** [comment]
okay, in that case can you load up an example of a previously analyzed data and see if (1) a 15 ms lag was used in that data, and (2) whether participation coefficient was calculated. Basically, loading up a matlab file containing the variable `NetMet` and checking whether you see the field `adjM15mslag.PC`, or whether you do not see it / see something else

**Comment by XuelinWangTvT** [comment]
Okay, thank you so much Tim!

**Comment by Timothysit** [comment]
The latest version of the pipeline runs density landscape across all lag used in earlier steps of the pipeline, so this 15 ms lag assumption is no longer needed.
